services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=bobtilfolket
      - POSTGRES_USER=nks_bob_api_user
      - POSTGRES_DB=nks_bob_api_db
  mockServer:
    image: mockserver/mockserver:latest
    ports:
      - "1080:1080"
    restart: on-failure
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: ./mocks
        target: /config
  bigQuery:
    image: ghcr.io/goccy/bigquery-emulator:latest
    platform: linux/x86_64
    ports:
      - "9050:9050"
      - "9060:9060"
    volumes:
      - type: bind
        source: ./mocks
        target: /data
    command: |
      --project=local --data-from-yaml=/data/bq-data.yaml
  wonderwall:
    image: ghcr.io/nais/wonderwall:2025-06-16-100734-4bf3b1b
    ports:
      - "3000:3000"
    command: >
      --openid.client-id='nks-bob-api'
      --openid.well-known-url=http://localhost:8899/entraid/.well-known/openid-configuration
      --ingress=http://localhost:3000
      --bind-address=0.0.0.0:3000
      --upstream-host=host.docker.internal:8080
      --log-level=debug
      --log-format=text
      --auto-login=true
    restart: on-failure
    environment:
      WONDERWALL_OPENID_CLIENT_JWK: >
        {
          "kty":"RSA",
          "alg":"RS256",
          "use":"sig",
          "p":"_xCPvqs85ZZVg460Qfot26rQoNRPTOVDo5p4nqH3ep6BK_5TvoU5LFXd26W-1V1Lc5fcvvftClPOT201xgat4DVtliNtoc8od_tWr190A3AzbsAVFOx0nKa5uhLBxP9SsPM84llp6PXF6QTMGFiPYuoLDaQQqL1K4BbHq3ZzF2M",
          "q":"7QLqW75zkfSDrn5rMoF50WXyB_ysNx6-2SvaXKGXaOn80IR7QW5vwkleJnsdz_1kr04rJws2p4HBJjUFfSJDi1Dapj7tbIwb0a1szDs6Y2fAa3DlzgXZCkoE2TIrW6UITgs14pI_a7RasclE71FpoZ78XNBvj3NmZugkNLBvRjs",
          "d":"f7aT4poed8uKdcSD95mvbfBdb6X-M86d99su0c390d6gWwYudeilDugH9PMwqUeUhY0tdaRVXr6rDDIKLSE-uEyaYKaramev0cG-J_QWYJU2Lx-4vDGNHAE7gC99o1Ee_LXqMDCBawMYyVcSWx7PxGQfzhSsARsAIbkarO1sg9zsqPS4exSMbK8wyCTPgRbnkB32_UdZSGbdSib1jSYyyoAItZ8oZHiltVsZIlA97kS4AGPtozde043NC7Ik0uEzgB5qJ_tR7vW8MfDrBj6da2NrLh0UH-q28dooBO1vEu0rvKZIescXYk9lk1ZakHhhpZaLykDOGzxCpronzP3_kQ",
          "e":"AQAB",
          "qi":"9kMIR6pEoiwN3M6O0n8bnh6c3KbLMoQQ1j8_Zyir7ZIlmRpWYl6HtK0VnD88zUuNKTrQa7-jfE5uAUa0PubzfRqybACb4S3HIAuSQP00_yCPzCSRrbpGRDFqq-8eWVwI9VdiN4oqkaaWcL1pd54IDcHIbfk-ZtNtZgsOlodeRMo",
          "dp":"VUecSAvI2JpjDRFxg326R2_dQWi6-uLMsq67FY7hx8WnOqZWKaUxcHllLENGguAmkgd8bv1F6-YJXNUO3Z7uE8DJWyGNTkSNK1CFsy0fBOdGywi-A7jrZFT6VBRhZRRY-YDaInPyzUkfWsGX26wAhPnrqCvqxgBEQJhdOh7obDE",
          "dq":"7EUfw92T8EhEjUrRKkQQYEK0iGnGdBxePLiOshEUky3PLT8kcBHbr17cUJgjHBiKqofOVNnE3i9nkOMCWcAyfUtY7KmGndL-WIP-FYplpnrjQzgEnuENgEhRlQOCXZWjNcnPKdKJDqF4WAtAgSIznz6SbSQMUoDD8IoyraPFCck",
          "n":"7CU8tTANiN6W_fD9SP1dK2vQvCkf7-nwvBYe5CfANV0_Bb0ZmQb77FVVsl1beJ7EYLz3cJmL8Is1RCHKUK_4ydqihNjEWTyZiQoj1i67pkqk_zRvfQa9raZR4uZbuBxx7dWUoPC6fFH2F_psAlHW0zf90fsLvhB6Aqq3uvO7XXqo8qNl9d_JSG0Rg_2QUYVb0WKmPVbbhgwtkFu0Tyuev-VZ9IzTbbr5wmZwEUVY7YAi73pDJkcZt5r2WjOF_cuIXe-O2vwbOrRgmJfHO9--mVLdATnEyrb6q2oy_75h6JjP-R4-TD1hyoFFoE2gmj-kSS6Z_Gggljs3Aw7--Nh10Q"
        }
    depends_on:
      - mock-oauth2-server
    extra_hosts:
      - localhost:host-gateway

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.2.1
    ports:
      - "8899:8080"
    restart: on-failure
    platform: linux/x86_64
    environment:
      JSON_CONFIG: |
        {
          "interactiveLogin": false,
          "tokenCallbacks": [
              {
              "issuerId": "entraid",
              "tokenExpiry": 3600,
              "requestMappings": [
                {
                  "requestParam": "grant_type",
                  "match": "authorization_code",
                  "claims": {
                    "aud": [
                      "nks-bob-api"
                    ],
                    "NAVident": "Z123456",
                    "groups": [
                      "admin"
                    ],
                    "azp": "consumer-client-id"
                  }
                },
                {
                  "requestParam": "requested_token_use",
                  "match": "on_behalf_of",
                  "claims": {
                    "aud": [
                      "nks-bob-api"
                    ],
                    "NAVident": "Z123456",
                    "groups": [
                      "admin"
                    ],
                    "azp": "consumer-client-id"
                  }
                },
                {
                  "requestParam": "client_id",
                  "match": "id",
                  "claims": {
                    "aud": [
                      "nks-bob-api"
                    ],
                    "NAVident": "Z123456",
                    "groups": [
                      "admin"
                    ],
                    "azp": "consumer-client-id"
                  }
                }
              ]
            }
          ]
        }
