apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: nks-aiautomatisering
  name: nks-bob-api
  namespace: nks-aiautomatisering
spec:
  envFrom:
  image: "{{ image }}"
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  accessPolicy:
    inbound:
      rules:
        - application: nks-bob
    outbound:
      rules:
        - application: nks-kbs
  azure:
    application:
      tenant: nav.no # Gjør at man kan logge på med vanlig konto i dev-gcp
      enabled: true
      allowAllUsers: true # TODO bare for testing.
    #  allowAllUsers: false
    #  claims:
    #    groups:
    #      - id: "dcb5ec4c-8027-428c-9dfd-15852388001c" # Administratorgruppe
    #      - id: "ad604335-b339-4804-82ee-fb5e2bcb87c9" # Brukergruppe
    sidecar:
      enabled: true
      autoLogin: true
  ingresses:
    - https://{{ingress}}/
  liveness:
    path: /internal/is_alive
    initialDelay: 20
    periodSeconds: 6
    timeout: 2
  readiness:
    path: /internal/is_ready
    initialDelay: 20
    periodSeconds: 6
    timeout: 10
