api {
  url = "http://localhost:8080"
  url = ${?NKS_BOB_API_URL}
  scope = "scope"
  scope = ${?NKS_BOB_API_SCOPE}
}

nais {
  tokenEndpoint = "http://localhost:3333/api/v1/token"
  tokenEndpoint = ${?NAIS_TOKEN_ENDPOINT}
}
